name: do-the-job
on: push
jobs:
  start-runner:
      name: Start self-hosted EC2 runner
      runs-on: ubuntu-latest
      outputs:
        label: ${{ steps.start-ec2-runner.outputs.label }}
        ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
      steps:
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4.0.2
          with:
            aws-access-key-id: ${{ secrets.AWS_EC2_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_EC2_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_EC2_REGION }}
        - name: Start EC2 runner
          id: start-ec2-runner
          uses: machulav/ec2-github-runner@v2.3.6
          with:
            mode: start
            github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
            ec2-image-id: ${{ secrets.AWS_EC2_IMAGE_AMI }}
            ec2-instance-type: c5.xlarge
            subnet-id: ${{ secrets.AWS_EC2_SUBNET }}
            security-group-id: ${{ secrets.AWS_EC2_SECURITY_GROUP }}
            pre-runner-script: |
              sudo yum update -y && \
              sudo yum install docker -y && \
              sudo yum install git -y && \
              sudo yum install libicu -y && \
              sudo systemctl enable docker
  
  benchmark:
    name: Benchmark Unstable
    needs: start-runner # required to start the main job when the runner is ready
    runs-on: ${{ needs.start-runner.outputs.label }} # run the job on the newly created runner
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Clone Valkey unstable
        uses: actions/checkout@v4
        with:
          repository: valkey-io/valkey
          path: ./valkey

      - name: Install 
        run: |
          sudo apt-get update && sudo apt-get install -y build-essential awscli

      - name: Make Valkey
        run: |
          pwd; \
          cd valkey; \
          ls; \
          make distclean; make; \
          src/valkey-server --daemonize yes --logfile valkey_log  --save "";
          src/valkey-benchmark --csv > results.csv; \
          cat results.csv;
  
  upload-benchmark:
    name: Upload benchmark to s3
    needs: 
      - start-runner
      - benchmark
    runs-on: ${{ needs.start-runner.outputs.label }}
    steps:
      - name: Install AWS cli.
        run: |
          sudo apt-get install -y awscli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_EC2_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_EC2_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_EC2_REGION }}
     
      - name: print dirs
        run: |
          pwd && \
          ls && \
          cd valkey && \
          ls

      # - name: Sync to S3
      #   run: aws s3 sync ~valkey/results.csv s3://${{ secrets.AWS_S3_BENCHMARK_UNSTABLE }}/

  stop-runner:
    name: Stop self-hosted EC2 runner
    needs:
      - start-runner # required to get output from the start-runner job
      - benchmark # required to wait when the main job is done
      - upload-benchmark
    runs-on: ubuntu-latest
    if: ${{ always() }} # required to stop the runner even if the error happened in the previous jobs
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_EC2_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_EC2_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_EC2_REGION }}
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-runner.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner.outputs.ec2-instance-id }}
